### ISSUE TITLE
Question about the performance of  AMINO ACID CONTACT PREDICTION Task.

### ISSUE THREAD

**Issue by zjs123** [RL4M/KeAP#4]
Hi, how can I get separate results of 6<seq<12, 12<seq<24, and 24<seq when I use run_contact.sh for fine-tuning and evaluation?
I can only get the overall L5, L2, and L metrics currently. 
<img width="1451" alt="image" src="https://github.com/RL4M/KeAP/assets/17922610/086c9b69-385f-4f10-a47c-0d52c85fbb61">
Thanks!!!

**Comment by yunxiangfu2001** [comment]
Hi, you can evaluate the results of 6<seq<12, 12<seq<24, and 24<seq reported in the paper by following this [issue](https://github.com/RL4M/KeAP/issues/3#issuecomment-1636113815)
